# See explaination in
# Blog config
keywords: MyBlueHorizon,云边,Blog,博客
author: MyBlueHorizon(云边)
description: 斜阳渐长，清风吹拂。
defaultTheme: default # light or dark or default

# icon
# If the is size is incorrect, please edit /source/css/style.styl
favicon: /images/favicon.webp
avatar: /images/logo.webp
logo_dir: /images/logo@2x.webp
logo_style: width:220px;

# Site-wide copyright settings
copyright:
  # If `show` is set to true, a copyright statement will be added to the bottom of each article. You can set this individually in the header of each post. For more information, please refer to the documentation
  # For example:
  # ---
  # title: xxx
  # copyright: "All rights reserved"
  # author: "Li Hua and Han Meimei"
  # ---
  # ---
  # title: xxx
  # copyright: disabled
  # ---
  show: true
  # Default copyright statement
  default: "本文著作权归作者所有，请勿转载。"
  # Show article author in the copyright statement
  show_author: true

# Site footbar
footbar:
  # Copyright statement.You can also use it as a footnote
  copyright:

# Social Links
# The key is the icon name of font-awesome 6, and the value is a link
# except for mail.
social:
  github: https://github.com/MyBlueHorizon
  mail: tianjizhishang@outlook.com
  rss: /atom.xml

# Nav menu
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  #About: /about
  #Links: /links

# Navbar rightbtn
rightbtn:
  back: true
  search: true # Thanks to Icarus for the search box code
  avatar: true
  darkLightToggle: true # A toggle switch for dark/light theme

# Other settings
useSummary: false # Opening it will use the automatically generated summary instead of the <!-- more --> you can configure to preview the article.

useTagCloud: false # Use tagcloud instead of tag list
tocMaxDepth: 6 # If you set 0, toc will not be generated. The maximum is 6.

# Comment
always_enable_comments: false # Always enable comments


gitalk:
  enable: true
  owner: 'MyBlueHorizon'
  repo: 'blog'
  client_id: 'ba63e4cd3321d81ab56a'
  client_secret: '71ee0a05921a119e4c02eee1baaa1f9ba9d6564b'
